// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AreaOfInterestResult model.
 */
@Fluent
public final class AreaOfInterestResult {
    /*
     * A bounding box for an area of interest inside an image.
     */
    @JsonProperty(value = "areaOfInterest", access = JsonProperty.Access.WRITE_ONLY)
    private BoundingRect areaOfInterest;

    /*
     * Id of the REST API request.
     */
    @JsonProperty(value = "requestId")
    private String requestId;

    /*
     * Image metadata.
     */
    @JsonProperty(value = "metadata")
    private ImageMetadata metadata;

    /**
     * Get the areaOfInterest property: A bounding box for an area of interest
     * inside an image.
     * 
     * @return the areaOfInterest value.
     */
    public BoundingRect getAreaOfInterest() {
        return this.areaOfInterest;
    }

    /**
     * Get the requestId property: Id of the REST API request.
     * 
     * @return the requestId value.
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Set the requestId property: Id of the REST API request.
     * 
     * @param requestId the requestId value to set.
     * @return the AreaOfInterestResult object itself.
     */
    public AreaOfInterestResult setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Get the metadata property: Image metadata.
     * 
     * @return the metadata value.
     */
    public ImageMetadata getMetadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: Image metadata.
     * 
     * @param metadata the metadata value to set.
     * @return the AreaOfInterestResult object itself.
     */
    public AreaOfInterestResult setMetadata(ImageMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
}
