// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The BoundingRect model.
 */
@Fluent
public final class BoundingRect {
    /*
     * X-coordinate of the top left point of the area, in pixels.
     */
    @JsonProperty(value = "x")
    private Integer x;

    /*
     * Y-coordinate of the top left point of the area, in pixels.
     */
    @JsonProperty(value = "y")
    private Integer y;

    /*
     * Width measured from the top-left point of the area, in pixels.
     */
    @JsonProperty(value = "w")
    private Integer w;

    /*
     * Height measured from the top-left point of the area, in pixels.
     */
    @JsonProperty(value = "h")
    private Integer h;

    /**
     * Get the x property: X-coordinate of the top left point of the area, in
     * pixels.
     * 
     * @return the x value.
     */
    public Integer getX() {
        return this.x;
    }

    /**
     * Set the x property: X-coordinate of the top left point of the area, in
     * pixels.
     * 
     * @param x the x value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setX(Integer x) {
        this.x = x;
        return this;
    }

    /**
     * Get the y property: Y-coordinate of the top left point of the area, in
     * pixels.
     * 
     * @return the y value.
     */
    public Integer getY() {
        return this.y;
    }

    /**
     * Set the y property: Y-coordinate of the top left point of the area, in
     * pixels.
     * 
     * @param y the y value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setY(Integer y) {
        this.y = y;
        return this;
    }

    /**
     * Get the w property: Width measured from the top-left point of the area,
     * in pixels.
     * 
     * @return the w value.
     */
    public Integer getW() {
        return this.w;
    }

    /**
     * Set the w property: Width measured from the top-left point of the area,
     * in pixels.
     * 
     * @param w the w value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setW(Integer w) {
        this.w = w;
        return this;
    }

    /**
     * Get the h property: Height measured from the top-left point of the area,
     * in pixels.
     * 
     * @return the h value.
     */
    public Integer getH() {
        return this.h;
    }

    /**
     * Set the h property: Height measured from the top-left point of the area,
     * in pixels.
     * 
     * @param h the h value to set.
     * @return the BoundingRect object itself.
     */
    public BoundingRect setH(Integer h) {
        this.h = h;
        return this;
    }
}
