// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Category model.
 */
@Fluent
public final class Category {
    /*
     * Name of the category.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * Scoring of the category.
     */
    @JsonProperty(value = "score")
    private Double score;

    /*
     * Details of the identified category.
     */
    @JsonProperty(value = "detail")
    private CategoryDetail detail;

    /**
     * Get the name property: Name of the category.
     * 
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: Name of the category.
     * 
     * @param name the name value to set.
     * @return the Category object itself.
     */
    public Category setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the score property: Scoring of the category.
     * 
     * @return the score value.
     */
    public Double getScore() {
        return this.score;
    }

    /**
     * Set the score property: Scoring of the category.
     * 
     * @param score the score value to set.
     * @return the Category object itself.
     */
    public Category setScore(Double score) {
        this.score = score;
        return this;
    }

    /**
     * Get the detail property: Details of the identified category.
     * 
     * @return the detail value.
     */
    public CategoryDetail getDetail() {
        return this.detail;
    }

    /**
     * Set the detail property: Details of the identified category.
     * 
     * @param detail the detail value to set.
     * @return the Category object itself.
     */
    public Category setDetail(CategoryDetail detail) {
        this.detail = detail;
        return this;
    }
}
