// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The DomainModelResults model.
 */
@Fluent
public final class DomainModelResults {
    /*
     * Model-specific response.
     */
    @JsonProperty(value = "result")
    private Object result;

    /*
     * Id of the REST API request.
     */
    @JsonProperty(value = "requestId")
    private String requestId;

    /*
     * Image metadata.
     */
    @JsonProperty(value = "metadata")
    private ImageMetadata metadata;

    /**
     * Get the result property: Model-specific response.
     * 
     * @return the result value.
     */
    public Object getResult() {
        return this.result;
    }

    /**
     * Set the result property: Model-specific response.
     * 
     * @param result the result value to set.
     * @return the DomainModelResults object itself.
     */
    public DomainModelResults setResult(Object result) {
        this.result = result;
        return this;
    }

    /**
     * Get the requestId property: Id of the REST API request.
     * 
     * @return the requestId value.
     */
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Set the requestId property: Id of the REST API request.
     * 
     * @param requestId the requestId value to set.
     * @return the DomainModelResults object itself.
     */
    public DomainModelResults setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * Get the metadata property: Image metadata.
     * 
     * @return the metadata value.
     */
    public ImageMetadata getMetadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: Image metadata.
     * 
     * @param metadata the metadata value to set.
     * @return the DomainModelResults object itself.
     */
    public DomainModelResults setMetadata(ImageMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
}
