// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/**
 * Defines values for Enum0.
 */
public final class Enum0 extends ExpandableStringEnum<Enum0> {
    /**
     * Static value en for Enum0.
     */
    public static final Enum0 EN = fromString("en");

    /**
     * Static value es for Enum0.
     */
    public static final Enum0 ES = fromString("es");

    /**
     * Static value ja for Enum0.
     */
    public static final Enum0 JA = fromString("ja");

    /**
     * Static value pt for Enum0.
     */
    public static final Enum0 PT = fromString("pt");

    /**
     * Static value zh for Enum0.
     */
    public static final Enum0 ZH = fromString("zh");

    /**
     * Creates or finds a Enum0 from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding Enum0.
     */
    @JsonCreator
    public static Enum0 fromString(String name) {
        return fromString(name, Enum0.class);
    }

    /**
     * @return known Enum0 values.
     */
    public static Collection<Enum0> values() {
        return values(Enum0.class);
    }
}
