// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The FaceDescription model.
 */
@Fluent
public final class FaceDescription {
    /*
     * Possible age of the face.
     */
    @JsonProperty(value = "age")
    private Integer age;

    /*
     * Possible gender of the face.
     */
    @JsonProperty(value = "gender")
    private Gender gender;

    /*
     * Rectangle in the image containing the identified face.
     */
    @JsonProperty(value = "faceRectangle")
    private FaceRectangle faceRectangle;

    /**
     * Get the age property: Possible age of the face.
     * 
     * @return the age value.
     */
    public Integer getAge() {
        return this.age;
    }

    /**
     * Set the age property: Possible age of the face.
     * 
     * @param age the age value to set.
     * @return the FaceDescription object itself.
     */
    public FaceDescription setAge(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * Get the gender property: Possible gender of the face.
     * 
     * @return the gender value.
     */
    public Gender getGender() {
        return this.gender;
    }

    /**
     * Set the gender property: Possible gender of the face.
     * 
     * @param gender the gender value to set.
     * @return the FaceDescription object itself.
     */
    public FaceDescription setGender(Gender gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Get the faceRectangle property: Rectangle in the image containing the
     * identified face.
     * 
     * @return the faceRectangle value.
     */
    public FaceRectangle getFaceRectangle() {
        return this.faceRectangle;
    }

    /**
     * Set the faceRectangle property: Rectangle in the image containing the
     * identified face.
     * 
     * @param faceRectangle the faceRectangle value to set.
     * @return the FaceDescription object itself.
     */
    public FaceDescription setFaceRectangle(FaceRectangle faceRectangle) {
        this.faceRectangle = faceRectangle;
        return this;
    }
}
