// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ImageMetadata model.
 */
@Fluent
public final class ImageMetadata {
    /*
     * Image width, in pixels.
     */
    @JsonProperty(value = "width")
    private Integer width;

    /*
     * Image height, in pixels.
     */
    @JsonProperty(value = "height")
    private Integer height;

    /*
     * Image format.
     */
    @JsonProperty(value = "format")
    private String format;

    /**
     * Get the width property: Image width, in pixels.
     * 
     * @return the width value.
     */
    public Integer getWidth() {
        return this.width;
    }

    /**
     * Set the width property: Image width, in pixels.
     * 
     * @param width the width value to set.
     * @return the ImageMetadata object itself.
     */
    public ImageMetadata setWidth(Integer width) {
        this.width = width;
        return this;
    }

    /**
     * Get the height property: Image height, in pixels.
     * 
     * @return the height value.
     */
    public Integer getHeight() {
        return this.height;
    }

    /**
     * Set the height property: Image height, in pixels.
     * 
     * @param height the height value to set.
     * @return the ImageMetadata object itself.
     */
    public ImageMetadata setHeight(Integer height) {
        this.height = height;
        return this;
    }

    /**
     * Get the format property: Image format.
     * 
     * @return the format value.
     */
    public String getFormat() {
        return this.format;
    }

    /**
     * Set the format property: Image format.
     * 
     * @param format the format value to set.
     * @return the ImageMetadata object itself.
     */
    public ImageMetadata setFormat(String format) {
        this.format = format;
        return this;
    }
}
