// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ImageType model.
 */
@Fluent
public final class ImageType {
    /*
     * Confidence level that the image is a clip art.
     */
    @JsonProperty(value = "clipArtType")
    private Integer clipArtType;

    /*
     * Confidence level that the image is a line drawing.
     */
    @JsonProperty(value = "lineDrawingType")
    private Integer lineDrawingType;

    /**
     * Get the clipArtType property: Confidence level that the image is a clip
     * art.
     * 
     * @return the clipArtType value.
     */
    public Integer getClipArtType() {
        return this.clipArtType;
    }

    /**
     * Set the clipArtType property: Confidence level that the image is a clip
     * art.
     * 
     * @param clipArtType the clipArtType value to set.
     * @return the ImageType object itself.
     */
    public ImageType setClipArtType(Integer clipArtType) {
        this.clipArtType = clipArtType;
        return this;
    }

    /**
     * Get the lineDrawingType property: Confidence level that the image is a
     * line drawing.
     * 
     * @return the lineDrawingType value.
     */
    public Integer getLineDrawingType() {
        return this.lineDrawingType;
    }

    /**
     * Set the lineDrawingType property: Confidence level that the image is a
     * line drawing.
     * 
     * @param lineDrawingType the lineDrawingType value to set.
     * @return the ImageType object itself.
     */
    public ImageType setLineDrawingType(Integer lineDrawingType) {
        this.lineDrawingType = lineDrawingType;
        return this;
    }
}
