// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
// 
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.vision.computervision.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The LandmarksModel model.
 */
@Fluent
public final class LandmarksModel {
    /*
     * Name of the landmark.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * Confidence level for the landmark recognition as a value ranging from 0
     * to 1.
     */
    @JsonProperty(value = "confidence")
    private Double confidence;

    /**
     * Get the name property: Name of the landmark.
     * 
     * @return the name value.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set the name property: Name of the landmark.
     * 
     * @param name the name value to set.
     * @return the LandmarksModel object itself.
     */
    public LandmarksModel setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the confidence property: Confidence level for the landmark
     * recognition as a value ranging from 0 to 1.
     * 
     * @return the confidence value.
     */
    public Double getConfidence() {
        return this.confidence;
    }

    /**
     * Set the confidence property: Confidence level for the landmark
     * recognition as a value ranging from 0 to 1.
     * 
     * @param confidence the confidence value to set.
     * @return the LandmarksModel object itself.
     */
    public LandmarksModel setConfidence(Double confidence) {
        this.confidence = confidence;
        return this;
    }
}
